### ISSUE TITLE
Buscar un sitio para las charlas del sábado

### ISSUE THREAD

**Issue by juandebravo** [tid-x/tid-x#2]

**Comment by ggarber** [comment]
Aquí alquilan salas para conferencias a precios asequibles: https://www.spaces-on.com/es/espacio-horas/list?q[capacity_gteq]=30&q[capacity_lteq]=60&q[company_city_eq]=Madrid&q[categories_id_in]=29

[Avenida America](https://www.spaces-on.com/es/espacio-horas/763-espacio-para-eventos-conferencias-madrid) (cerca Emilio Vargas :P), 50 personas, 185$/dia
[Barrio Salamanca](https://www.spaces-on.com/es/espacio-horas/957-sala-3-en-barrio-de-salamanca-madrid), 35 personas, 250$/dia

**Comment by dperales** [comment]
aqui os dejo otro https://www.campus.co/madrid/en

**Comment by alvarosperez** [comment]
El campus de google que comenta @dperales es gratuito, además

**Comment by ggarber** [comment]
Yo creo que en campus no nos van a dejar tener un evento privado, pero lo pregunto la próxima vez que me pase por allí.

**Comment by juandebravo** [comment]
[Worktel](https://worktel.com/hotel/583/Sala-NY-(70-personas)?&date=24%2F02%2F2018&latitude=40.4167754&longitude=-3.7037901999999576&from=900&to=1800&fullslot=&minFullSize=MIN20&singleSlot=&city=Madrid,%20Spain&type=salas-de-reuniones&provider=centros) tiene buena pinta para buscar sitios.

No creo que encontremos sitios gratuitos, pero tienen buenas opciones como [esta](https://worktel.com/hotel/277/Sala-hasta-80-pax-?&date=24%2F02%2F2018&latitude=40.4167754&longitude=-3.7037901999999576&from=900&to=1800&fullslot=&minFullSize=MIN20&singleSlot=&filters=true&city=Madrid,%20Spain&type=salas-de-reuniones&provider=centros)

**Comment by pedroconcejero** [comment]
El [grupo R de madRid](https://www.meetup.com/es-ES/Grupo-de-Usuarios-de-R-de-Madrid/) nos reunimos gratuitamente en [The Cube](https://www.thecubemadrid.com/), es cuestión de preguntarles.

**Comment by cgalisteo** [comment]
The Cube no es que esté precisamente céntrico. No digo que haya que descartarlo, sólo que se tenga en cuenta :-)

**Comment by rafaelrebolleda** [comment]
Podría mover la [Central de Diseño en Matadero](http://www.mataderomadrid.org/central-de-diseno.html)... hace un par se semanas montamos ahí una parte del [SDGC17](https://www.service-design-network.org/sdgc/sdgc17). También podría tantear el [Media Lab Prado](http://medialab-prado.es/) o [ESNE](http://esne.es).

Hace tiempo montamos quedadas JS y algún otro evento en CAMON, en Moncloa. También montamos muchos madrid.rb en [Utopic_us](https://www.utopicus.es/es/page/servicios-eventos). El Irish Rover en Av. de Brasil también se ha prestado a pequeños eventos en el pasado como el MeetApp. En Teleco UPM nos acogieron la Conferencia Rails varias veces gratuitamente.

[Impact HUB](https://madrid.impacthub.net/eventos/) podría ser otra opción, probablemente cara...

**Comment by juandebravo** [comment]
Gracias a todos por las aportaciones 🏩. En breve comunicaremos en el grupo de Telegram que el evento tendrá lugar en Google Campus.
