### ISSUE TITLE
Serverless Architecture: The closest way to NoOps

### ISSUE THREAD

**Issue by albertobaselga** [tid-x/tid-x#26]
### Serverless Architecture: The closest way to NoOps

How current Serverless patterns can help you on minimising maintenance time and risks.

### Description

_Let's be pragmatic, please leave a comment if you would be more interested on a theoretical session (more scope) or on something more hands-on (less scope)._

### Estimated time

45min

### Level (Initiate, Padawan, Knight, Master)

_TBD (Based on feedback)_

**Comment by juandebravo** [comment]
@albertobaselga, tu charla había sido seleccionada pero como hemos comentado renuncias por pico de trabajo. Gracias en cualquier caso por tu propuesta 👍
