### ISSUE TITLE
Getting Started with Tensorflow

### ISSUE THREAD

**Issue by ggarber** [tid-x/tid-x#56]
### Title

Getting Started with Tensorflow

### Description

The talk will start explain what the hell is this Tensorflow thing and show how to use it at a low level for a typical regression (aka prediction) case and how to use it at a higher level for the typical image recognition use cases.

### Estimated time

45 mins (can be shorter if needed)

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@ggarber, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
