### ISSUE TITLE
Real World Raspberry Pi: own your phone!

### ISSUE THREAD

**Issue by jagui** [tid-x/tid-x#57]
### Title

Real World Raspberry Pi: own your phone!

### Description

Did you know that your fixed telephone line is (quite probably) a VoIP line running the SIP protocol? Did you buy a Raspberry Pi and you're only using it for streaming pirated media?
Do you work from home and you're sick of getting unsolicited commercial calls?

Please join me in this Real World Raspberry Pi session and you'll learn how harness the power of PJSIP for rejecting or diverting calls or whatever floats your boat. 

DIY is fun, but DIY-telephony is even funnier. And that's why you guys joined TID in the 1st place, right? 

NB: please note that this can easily become a hands-on workshop.

### Estimated time

30m tops

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@jagui, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
