### ISSUE TITLE
Becoming "as a Service"

### ISSUE THREAD

**Issue by tungamajunga** [tid-x/tid-x#58]
### Title

Becoming  "as a Service"

### Description

The advent of Cloud services has enabled new architectures styles and the success of a software products goes beyond being an installable product. Instead it needs to be a cloud service. This talk discusses the implications and strategies for transforming products into cloud services.

### Estimated time

40 min

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@tungamajunga, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
