### ISSUE TITLE
Messaging, EDA, Streams, Event Sourcing, CQRS. Connecting the dots

### ISSUE THREAD

**Issue by tungamajunga** [tid-x/tid-x#59]
### Title

Messaging, EDA, Streams, Event Sourcing, CQRS. Connecting the dots.

### Description

Over the past 20 years, different patterns and technologies for interchanging messages and events between parts of software systems has appeared and evolved. This talk tries to connect the concepts between the different approaches  

### Estimated time

40 min

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@tungamajunga, tu charla no ha seleccionada para la agenda de TID-X 2018 (hay otra que sí 😊). Muchas gracias en cualquier caso por la propuesta.
