### ISSUE TITLE
OpenAPI Specification

### ISSUE THREAD

**Issue by javiersigler** [tid-x/tid-x#60]
### Title

OpenAPI Specification

### Description

OpenAPI Specification, formerly Swagger, is emerging like the de facto standard for describing, producing, consuming, and visualizing RESTful Web services. Adopted by the Linux Foundation and supported by several leading companies like Google or Microsoft, it is dramatically increasing its popularity among the developers.
In this talk we will give a brief description of OpenAPI as well as analyzing their advantages and, limitations. Finally, we will offer some practical hints and tips.

### Estimated time

40 min

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by ggarber** [comment]
It would be great if somebody who hates Swagger/OpenAPI could participate in the talk too to give different points of view.   For example none of the Google APIs use this format to describe their APIs, they use services descriptions based on protobuf/grpc/...

**Comment by juandebravo** [comment]
@javiersigler, tu charla no ha seleccionada para la agenda de TID-X 2018. Muchas gracias en cualquier caso por la propuesta.
