### ISSUE TITLE
Hblend - Packaging web apps like a Viking God

### ISSUE THREAD

**Issue by fulldump** [tid-x/tid-x#61]
### Title

Hblend - Packaging web apps like a Viking God

### Description

Web technologies are in frenetic evolution. Every day dozens of new fancy tools appear in scene and every day, dozens of old fancy tools die. You can start a new project from scratch today that will probably be impossible to build in a few months. Different web languages are treated as different things although they are part of the same thing. Hblend manage dependencies and code from a sightly different point of view to make packaging easy while maintain your project buildable over the time.

### Estimated time

20 minutes.

### Level (Initiate, Padawan, Knight, Master)

Level is initiate. (I guess anyone knows something about html, css and js)

Audience might be multidisciplinar; our suggestion is to avoid master classes
that might require deep knowledge about the subject.

**Comment by juandebravo** [comment]
@fulldump, tu charla no ha seleccionada para la agenda de TID-X 2018. Muchas gracias en cualquier caso por la propuesta.
