### ISSUE TITLE
Lambdas everywhere

### ISSUE THREAD

**Issue by fulldump** [tid-x/tid-x#62]
### Title

Lambdas everywhere

### Description

Introducion to lambdas in programming languages and the jump to lambdas in the cloud.

### Estimated time

From 30 minutes.

### Level (Initiate, Padawan, Knight, Master)

Initiate, for all audiences.

Audience might be multidisciplinar; our suggestion is to avoid master classes
that might require deep knowledge about the subject.

**Comment by juandebravo** [comment]
@fulldump, tu charla no ha seleccionada para la agenda de TID-X 2018. Muchas gracias en cualquier caso por la propuesta.
