### ISSUE TITLE
Naturalized URLs in APIs 

### ISSUE THREAD

**Issue by fulldump** [tid-x/tid-x#63]
### Title

Naturalized URLs in APIs 

### Description

Lots of routing libraries treat the URL as a string without structure, without semantic. Let's treat URLs like if they were paths.

### Estimated timer

20 minutes

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@fulldump, tu charla no ha seleccionada para la agenda de TID-X 2018. Muchas gracias en cualquier caso por la propuesta.
