### ISSUE TITLE
Advanced orchestration techniques in Kubernetes

### ISSUE THREAD

**Issue by javierprovecho** [tid-x/tid-x#65]
### Title

Advanced orchestration techniques in Kubernetes.

> ... or how I stopped hacking and love Kubernetes

### Description

Most of the people trust their orchestrator of preference with the placement of their services on a distributed cluster. But in some cases , two replicas can't be scheduled on the same node for performance or redundancy reasons. 

In the meanwhile, we may need to update the manifests of our services (ex: port change) and perform a rolling update in real time.

Last but not least, we want to own the decisions that the orchestrator makes when killing / rescheduling our services, and not viceversa. Most quorum-based software don't tolerate a number of available replicas inferior than majority of the total size.

In this talk, I'll explain some native APIs that Kubernetes expose for this kind of scenarios.

> ... and also, some hacks I did in the past for lower level orchestrators.

### Estimated duration

40 minutes.

### Level (Initiate, Padawan, Knight, Master)

Padawan in DevOps, any experience in container orchestrators or distributed systems is valid.

**Comment by juandebravo** [comment]
@javierprovecho, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
