### ISSUE TITLE
Chatting with your app // Moving UI to IM

### ISSUE THREAD

**Issue by frsela** [tid-x/tid-x#66]
### Title

Chatting with your app

### Description

NLPs is the new wave, the UI is moving to IM apps (where your users are)

This talk is an introduction to NLP using engines like DialogFlow (Google) and start controlling your devices with your IM app

### Estimated time

30 - 60 min

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@frsela, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
