### ISSUE TITLE
Brining native perfomance to the web with WebAssembly

### ISSUE THREAD

**Issue by robjperez** [tid-x/tid-x#68]
### Title

Brining native perfomance to the web with WebAssembly

### Description

We will introduce WebAssembly and see some examples

### Estimated time

30 mins

### Level (Initiate, Padawan, Knight, Master)

Padawan

**Comment by juandebravo** [comment]
@robjperez, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
