### ISSUE TITLE
Any time gone by was better. Retrocomputing at 201X

### ISSUE THREAD

**Issue by robjperez** [tid-x/tid-x#69]
### Title

Any time gone by was better. Retrocomputing at 201X

### Description

We will talk about how old systems are living a second life nowadays. Expect hearing about emulators, FPGAs, Dynamic Recompilation or VMs

### Estimated time

30 mins

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@robjperez, tu charla no ha seleccionada para la agenda de TID-X 2018 (hay otra que sí 😊). Muchas gracias por la propuesta.
