### ISSUE TITLE
How we use at Zalando an event source architecture at the core of our system

### ISSUE THREAD

**Issue by lerovitch** [tid-x/tid-x#72]
### Title

How we use at Zalando an event source architecture at the core of our system

### Description

At Zalando we are migrating big old monoliths into a smaller decoupled microservices which uses a message broker component as the heart of its architecture.
This message broker has shifted a previous heavily REST based request / response architecture into an event-sourcing paradigm. 
In this talk I would focus on some use cases related to our team domain that would prove benefits and drawbacks of this event-sourcing system and how different requirements have better fit in it.

### Estimated time

40 min

### Level (Initiate, Padawan, Knight, Master)
Padawan

**Comment by juandebravo** [comment]
@lerovitch, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
