### ISSUE TITLE
Onion Architecture for Scala

### ISSUE THREAD

**Issue by sortega** [tid-x/tid-x#75]
### Onion Architecture for Scala

A code-driven incarnation of the onion architecture taking advantage of the Scala language constructions.

### Description

Onion architectures put the domain in the center and aim to decouple it from the mundane details of the real world: those database, network connections and other infrastructure details. When your target language supports higher kinds you can make a cleaner separation of concerns without resorting to black magic. We will see how.

### Estimated time

30-40 minutes

### Level (Initiate, Padawan, Knight, Master)

Initiate to Knight (special effort will be done for not losing Scala neofites)

**Comment by juandebravo** [comment]
@sortega, tu charla no ha seleccionada para la agenda de TID-X 2018 (hay otra que sí 😊 ). Muchas gracias en cualquier caso por la propuesta.
