### ISSUE TITLE
How I ended up in the hall of shame... repeatedly!

### ISSUE THREAD

**Issue by tomekwszelaki** [tid-x/tid-x#84]
### Title

How I ended up in the hall of shame... repeatedly!

### Description

In many languages there's a saying: "Smart people learn from their mistakes", but I think that's dumb! Mistakes are costly and painful and all around bleh! I propose a new saying: "Smart people learn from **OTHER PEOPLE**'s mistakes" - there, now that's an approach I like and that's precisely what this talk is all about. 

Over the course of my career as a tester I fell in to many pitfalls and committed many errors and I want to tell you about them in hopes that it'll help you avoid these mistakes and the shame they cause.

### Estimated time

30 minutes + Q&A session afterwards

### Level (Initiate, Padawan, Knight, Master)

Initiate/Padawan

**Comment by juandebravo** [comment]
@tomekwszelaki, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
