### ISSUE TITLE
What the hell happened with Web development?

### ISSUE THREAD

**Issue by delapuente** [tid-x/tid-x#86]
### Title

What the hell happened with Web development?

### Description

I don't know about your case but I started programming on the Web with a notepad, a browser and some reference books. Gone are those days where you faced a new project with almost no doubts about the tools and pipelines to choose. Nowadays, I can not imagine what a newcomer feels when facing web development for the first time. This talk is both a review and a dissection of the web programming scene.

### Estimated time

30 to 40

### Level (Initiate, Padawan, Knight, Master)

All levels.

**Comment by juandebravo** [comment]
@delapuente, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
