### ISSUE TITLE
Porting DIV2 to JavaScript

### ISSUE THREAD

**Issue by delapuente** [tid-x/tid-x#87]
### Title

Porting DIV2 to JavaScript

### Description

[DIV2](https://es.wikipedia.org/wiki/DIV_Games_Studio) is a Spanish game programming language for MS-DOS and Windows platforms that featured a Linux-process-like paradigm for approaching games modelling. [DIV2js](https://github.com/delapuente/div2js) is my intent to transpile DIV2 to JavaScript in my free-time. This is a technical talks about parsers, ArrayBuffers, state machines, greenlets, architecture and pipelines.

### Estimated time

40 min.

### Level (Initiate, Padawan, Knight, Master)

Padawan

**Comment by juandebravo** [comment]
@delapuente, tu charla no ha seleccionada para la agenda de TID-X 2018 (hay otra que sí 😊 ). Muchas gracias en cualquier caso por la propuesta.
