### ISSUE TITLE
From TID to the sky

### ISSUE THREAD

**Issue by delapuente** [tid-x/tid-x#88]
### Title

From TID to the sky.

### Description

TID gave me the chance of meeting amazing people and joining state-of-the-art projects. It certainly influenced my personality and changed my life. TID, Firefox OS and the people in the team motivated me to pursue higher and more challenging endeavours. This talk speaks of TID, the good and not-as-good parts.

### Estimated time

30 min.

### Level (Initiate, Padawan, Knight, Master)

All levels.

**Comment by juandebravo** [comment]
@delapuente, tu charla no ha seleccionada para la agenda de TID-X 2018 (hay otra que sí 😊 ). Muchas gracias en cualquier caso por la propuesta.
