### ISSUE TITLE
Rust 101

### ISSUE THREAD

**Issue by ferjm** [tid-x/tid-x#89]
### Title
Rust 101
### Description
Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety. If you ask users "what's the catch", they'll tell you about the challenging learning curve that this powerful new tool requires.

Presented by Mozilla engineers, this tutorial assumes familiarity with basic programming concepts (loops, conditionals, functions) but will require no prior experience with strongly typed languages, Rust, or systems programming. You'll learn the key concepts necessary for successful Rust programming, as well as how to continue exploring and even contribute to the language after TID-X.
### Estimated time
30-40 minutes.
### Level (Initiate, Padawan, Knight, Master)
Initiate-Padawan.

**Comment by juandebravo** [comment]
@ferjm, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
