### ISSUE TITLE
Keynote speaker

### ISSUE THREAD

**Issue by juandebravo** [tid-x/tid-x#9]
¿Te apetece que alguna persona en especial nos diera una keynote para inaugurar el evento? Tanto si está relacionada con TID o no, nos encantaría recibir opciones realistas de speakers para comenzar las charlas con una keynote.

Incluye un comentario con un nombre y por qué te apetece que sea él quien de la Keynote.

Si quieres apoyar a una persona como keynote speaker, pulsa 👍 en el comentario.

Si no quieres apoyar a una persona como keynote speaker, pulsa 👎 en el comentario.

Si te da igual, no hagas nada.

**Comment by ggarber** [comment]
https://twitter.com/ladybenko

**Comment by palmerabollo** [comment]
Me ha dicho Elon que le parte la tarde.

**Comment by palmerabollo** [comment]
https://twitter.com/javisantana Javi Santana, CTO Carto

**Comment by juandebravo** [comment]
https://twitter.com/carlosdomingo Carlos Domingo, ex-Consejero Delegado de TID y fundador de [SPiCE Liquid VC](https://www.spicevc.com/)

**Comment by juandebravo** [comment]
[Ian Small](https://twitter.com/iansmall), no recuerdo su último cargo en Telefonica pero es de los mejores storytellers que he tenido la suerte de escuchar.

**Comment by rafaelrebolleda** [comment]
[Javier Zorzano](https://twitter.com/zorzano) FTW.
