### ISSUE TITLE
The mindful developer - Becoming Jedi developer

### ISSUE THREAD

**Issue by shaykec** [tid-x/tid-x#90]
### Title

The mindful developer - Becoming a Jedi developer

### Description

Staying in focus, being creative and maintaining your sanity are becoming some of the biggest challenges in a developer life.
In this short talk, we will explore the benefits and power that developers can gain via mindfulness practice. 

Sample code included!

### Estimated time

15 minutes

### Level (Initiate, Padawan, Knight, Master)

Initiate

**Comment by juandebravo** [comment]
@shaykec, tu charla ha seleccionada para la agenda de TID-X 2018. Muchas gracias por la propuesta. En breve me pondré en contacto contigo para siguientes pasos.
