### ISSUE TITLE
How our brain works: engineering for human perception.

### ISSUE THREAD

**Issue by rafaelrebolleda** [tid-x/tid-x#91]
### Title

How our brain works: engineering for human perception.

### Description

In this talk I'd like to share some facts about how human perceive and process reality so we can make informed engineering decisions about performance, loading times and priorities, motion, animation and rendering in general. We'll see how this impacts not only front-end development but also architectural choices.

### Estimated time

30 min + QA.

### Level (Initiate, Padawan, Knight, Master)

Initiate, Padawan.

**Comment by juandebravo** [comment]
@rafaelrebolleda, tu charla no ha seleccionada para la agenda de TID-X 2018. Muchas gracias en cualquier caso por la propuesta.
